GET http://localhost:8080/CA1/api/person/test

###
POST http://localhost:8080/CA1/api/xxx

#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}